version: "3.8"
services:

  api:
    container_name: Api
    build: .
    ports:
      - "5000:5000"

  db:
    image: postgres:latest
    container_name: Psql
    env_file:
      - database.env # configure postgres
    restart: unless-stopped
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down

volumes:
  database-data:
