version: '3'

services:
  front:
    container_name: VueJs
    command: npm start
    build:
      context: ../timemanager-front/.
      dockerfile: Dockerfile
    image: timemanagervuejsmehdi:latetst
    # - '../timemanager-front/.:/app'
    # - '/app/node_modules'
    ports:
      - '8081:8081'
  
  web:
    build: .
    # image: docker.io/codereviewvideos/docker-phoenix
    command: >
      bash -c "mix deps.get --force && mix ecto.create && mix ecto.migrate && mix phx.server"
    # bash -c "mix deps.get --force && mix ecto.create && yes | mix phx.gen.json Account User users username:string email:string password_hash:string role:string --force && yes | mix phx.gen.json Timer Clock clocks time:datetime status:boolean user:references:users --force && yes | mix phx.gen.json Timer WorkingTimes workingtimes start:datetime end:datetime user:references:users --force \
    # && ls ./priv/repo/migrations && mix ecto.migrate && mix phx.server"
    # mix ecto.create && yes | mix phx.gen.json Account User users username:string email:string &&
    #      yes | mix phx.gen.json Timer Clock clocks time:datetime status:boolean user:references:users &&
    #      yes | mix phx.gen.json Timer WorkingTimes workingtimes start:datetime end:datetime user:references:users &&
#&& mix ecto.migrate  Genius I'm
    # command: mix phx.gen.json Timer WorkingTimes workingtimes start:datetime end:datetime user:references:users --force
    # command: mix ecto.migrate --force
    # command: mix phx.server
    environment:
      - MIX_ENV=dev
      - PORT=4000
      - DATABASE_URL=postgres://postgres:postgres@mypostgres:5432/timemanager_dev
      - HOSTNAME_URL=mypostgres
    # volumes:
    #   - .:/app
    ports:
      - "4000:4000"
    links:
      - mypostgres
    depends_on:
      - mypostgres

  mypostgres:
    image: postgres:13
    # volumes:
    #     - "./volumes/postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: always
