version: '3'

services:
  web:
    build: .
    # image: docker.io/codereviewvideos/docker-phoenix
    command: >
      bash -c "mix deps.get --force && mix phx.gen.json Account User users username:string email:string --force &&
           mix phx.gen.json Timer Clock clocks time:datetime status:boolean user:references:users --force &&
           mix phx.gen.json Timer WorkingTimes workingtimes start:datetime end:datetime user:references:users --force && echo Y | mix ecto.migrate && mix phx.server"

    # command: mix phx.gen.json Timer WorkingTimes workingtimes start:datetime end:datetime user:references:users --force
    # command: mix ecto.migrate --force
    # command: mix phx.server
    environment:
      - MIX_ENV=dev
      - PORT=4000
      - DATABASE_URL=postgres://postgres:postgres@mypostgres:5432/tm_db
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    links:
      - mypostgres
    depends_on:
      - mypostgres

  mypostgres:
    image: postgres:13
    volumes:
        - "./volumes/postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: always
